[project]
name = "pydantic-ai-support-agent"
version = "0.1.0"
description = "An example project for using Galileo with PydanticAI."
readme = "README.md"
requires-python = ">=3.11, <3.14"
dependencies = [
    "galileo[otel]>=1.40.0",
    "pydantic-ai>=1.0.0",
]
